name: emp
channels:
  - conda-forge
dependencies:
  - numpy
  - ipykernel
  - tqdm
  - ca-certificates
  - openssl
  - pandas
  - pytest
  - matplotlib
  - certifi
  - pyyaml
prefix: C:\Users\harrylloyd\miniforge3\envs\emp
